//32-2 Recap API Concept , Intro to JSON
const person={
    name:'toukir',
    age:22,
    address:'Dhaka',
    profession:'student',
    country:'Bangladesh',
    favSubject:['Math','English','Bangla','ICT'],
    isMarried:false,
    friends:[
        {name:'Avi',age:23},
        {name:'1229',age:24},
        {name:'Salma',age:25},
        {name:'toukir',age:26},
    ],
    hasGF:false,
    gfName:'',
    siblings:['sister','brother'],
    isSingle:true,
    isRich:false,
    isHappy:true,
    isHealthy:true,
    isActive:true,
    isStudent:true,
    isEmployed:false,
    isEntrepreneur:false,
    isTraveler:true,
    isFoodie:true,
    isGamer:false,
    isReader:true,
    isWriter:false,
    isArtist:false,
    isMusician:false,
    isDancer:false,
    isSinger:false,
    isActor:false,
    isDirector:false,
    isProducer:false,
    isPhotographer:false,
    isBlogger:true,
    isVlogger:false,
    isYoutuber:false,
    isTiktoker:false,
    isInstagrammer:true,
    isFacebooker:true,
    isTwitterer:false,
    isLinkedIn:false,
    isSnapchatter:false,
    isRedditor:false,
    isQuoran:false,
    isPinterestUser:false,
    isTumblrUser:false,
    isMediumUser:false    ,
    isSubstackUser:false,
    isPatreonUser:false,
}
console.log(person,'\n\ntyepeof person:',typeof person);
const personJSON=JSON.stringify(person);//Object converted in to String
console.log(personJSON,'\n\ntypeof personJSON:',typeof personJSON);// string
const personParsed=JSON.parse(personJSON);//String converted in to Object
console.log(personParsed,'\n\ntypeof personParsed:',typeof personParsed); // object